# readthedocs.yml
version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "mambaforge-22.9"
    
conda:
  environment: environment.yml
  
# Define the steps to build the documentation
sphinx:
  configuration: docs/source/conf.py  # Path to your Sphinx config file

