version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"

python:
  version: 3.11
  install:
    - conda:
        environment: environment.yml  # This is fine, just this one is needed
  script:
    - pip install -e .  # Only install your package in editable mode

sphinx:
  configuration: docs/conf.py